version: "3.1"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
      - "443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default
      - ./docker/nginx/nginx.conf:/etc/nginx/sites-available/default
    links:
      - app
    env_file: ./.env

  app:
    image: node:latest
    container_name: my-app
    working_dir: /application
    volumes:
      - .:/application
    links:
      - mysql
      - redis
      - mailhog
    ports:
      - "9000"
    entrypoint: /application/start_application.sh
    env_file: ./.env
    environment:
      "NODE_ENV": "development"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: "db-name"
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
